baseURL = 'https://scicomp-durham.github.io/COMP52315/'
DefaultContentLanguage = 'en'
title = 'COMP52315 – Performance Engineering, Vectorisation and GPU Programming'

staticDir = ['static']
disablePathToLower = false
enableGitInfo = true
enableRobotsTXT = false

theme = 'book'

disableKinds = ['taxonomy', 'taxonomyTerm']
# Needed for katex shortcodes
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableofcontents]
    startLevel = 1
    ordered = false
    endLevel = 4
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokailight'
    tabWidth = 8

[params]
BookSection = '/'
BookSearch = false
BookComments = false
BookToc = true
BookRepo = 'https://github.com/scicomp-durham/COMP52315'
BookLogo = 'logo.svg'
ModulePage = 'https://www.dur.ac.uk/postgraduate.modules/module_description/?year=2022&module_code=COMP52315'
BookEditPath = 'edit/main/site/content'
ImageDir = 'images'
CopyRight = '&copy; 2020--2023 [Lawrence Mitchell](mailto:lawrence@wence.uk), [Massimiliano Fasi](mailto:massimiliano.fasi@durham.ac.uk), and [Durham University](https://www.dur.ac.uk/).'
